config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :teams do
    resources :team_memberships
  end

  resources :repos do
    resources :pull_requests, controller: :repo_pull_requests
  end

  resources :pull_requests, only: [:new, :create] do
    resources :review_assignments
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :pull_requests, only: :create
    end
  end

  root 'welcome#index'
end

app/models/repo.rb
# Models repositories including validations
class Repo < ActiveRecord::Base
  validates :name,     presence: true, uniqueness: { scope: :company_id }
  validates :url,      presence: true, uniqueness: true
  validates :owner,    presence: true
  validates :company,  presence: true

  belongs_to :company
  belongs_to :owner, class_name: User

  has_and_belongs_to_many :teams # rubocop:disable Rails/HasAndBelongsToMany

  has_many :pull_requests
end

app/models/repos/team_finder.rb
module Repos
  # Finds teams tied to repos based on a user's team memberships
  class TeamFinder
    RepoTeamConflict = Class.new(ReviewRandomizerError)
    RepoTeamMismatch = Class.new(ReviewRandomizerError)

    def initialize(repo)
      @repo = repo
    end

    def for_team_member!(user)
      for_team_member(user).tap do |team|
        fail(
          RepoTeamMismatch,
          'User not on team tied to pull request\'s repo'
        ) if team.nil?
      end
    end

    def for_team_member(team_member)
      teams_for_team_member(team_member).tap do |teams|
        if teams.size > 1
          fail RepoTeamConflict, 'Multiple teams exist for the repo'
        end
      end.first
    end

    private

    def teams_for_team_member(team_member)
      repo.teams.select do |team|
        team.users.where(id: team_member.id).exists? ||
          team.team_memberships.where(id: team_member.id).exists?
      end
    end

    attr_reader :repo
  end
end

app/controllers/repos_controller.rb
# Controllers for repositories that will have PRs opened against it
class ReposController < ApplicationController
  respond_to :html

  load_and_authorize_resource through: :current_company

  def create
    @repo.save
    respond_with @repo
  end

  def update
    @repo.update(repo_params)
    respond_with @repo
  end

  def destroy
    @repo.destroy
    respond_with @repo
  end

  private

  def repo_params
    params.require(:repo).permit(
      :organization, :name, :description, :url
    ).tap do |params|
      params[:owner] = current_user
    end
  end
end

app/helpers/repos_helper.rb
# Helper methods for repos
module ReposHelper
end

app/views/repos/_form.html.erb
<%= simple_form_for(@repo) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :organization %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/repos/edit.html.erb
<% content_for(:title) do %>
  Editing Repo
<% end %>

<%= render 'form' %>

<%= link_to 'Show', @repo %> |
<%= link_to 'Back', repos_path %>

app/views/repos/index.html.erb
<% content_for(:title) do %>
  Listing Repos
<% end %>

<table>
  <thead>
    <tr>
      <th>Organization</th>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repos.each do |repo| %>
      <tr>
        <td><%= repo.organization %></td>
        <td><%= repo.name %></td>
        <td><%= repo.description %></td>
        <td><%= repo.url %></td>
        <td><%= repo.owner.name %></td>
        <td><%= link_to 'Show', repo %></td>
        <td><%= link_to 'Edit', edit_repo_path(repo) %></td>
        <td><%= link_to 'Destroy', repo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repo', new_repo_path %>

app/views/repos/new.html.erb
<% content_for(:title) do %>
  New Repo
<% end %>

<%= render 'form' %>

<%= link_to 'Back', repos_path %>

app/views/repos/show.html.erb
<% content_for(:title) do %>
  <%= @repo.name %> Repo
<% end %>

<p>
  <strong>Organization:</strong>
  <%= @repo.organization %>
</p>

<p>
  <strong>Name:</strong>
  <%= @repo.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @repo.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @repo.url %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @repo.owner.name %>
</p>

<p>
  <strong>Pull Requests:</strong>
  <ul>
    <% @repo.pull_requests.each do |pull_request| %>
      <li><%= pull_request.title %></li>
    <% end %>
  </ul>
</p>

<%= link_to 'Manage Pull Requests', repo_pull_requests_path(@repo) %> |
<%= link_to 'Edit', edit_repo_path(@repo) %> |
<%= link_to 'Back', repos_path %>