config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :teams do
    resources :team_memberships
  end

  resources :repos do
    resources :pull_requests, controller: :repo_pull_requests
  end

  resources :pull_requests, only: [:new, :create] do
    resources :review_assignments
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :pull_requests, only: :create
    end
  end

  root 'welcome#index'
end

app/models/review_assignment.rb
# Models assignments for reviewing pull requests
class ReviewAssignment < ActiveRecord::Base
  belongs_to :pull_request
  belongs_to :team_membership
  has_one :team, through: :team_membership
  has_one :user, through: :team_membership

  validates :pull_request,    presence: true
  validates :team_membership, presence: true

  def assignee_handle
    user ? user.handle : team_membership.handle
  end
end

app/controllers/review_assignments_controller.rb
# Controller for assignements to review pull requests
class ReviewAssignmentsController < ApplicationController
  respond_to :html

  load_resource :pull_request
  load_and_authorize_resource :review_assignment, through: :pull_request

  def create
    @review_assignment.save
    respond_with @pull_request, @review_assignment
  end

  def update
    @review_assignment.update(review_assignment_params)
    respond_with @pull_request, @review_assignment
  end

  def destroy
    @review_assignment.destroy
    respond_with @pull_request, @review_assignment
  end

  private

  def review_assignment_params
    params
      .require(:review_assignment)
      .permit(:pull_request_id, :team_membership_id)
  end
end

app/helpers/review_assignments_helper.rb
# View helper for review assignments
module ReviewAssignmentsHelper
end

app/views/review_assignments/_form.html.erb
<%= simple_form_for([@pull_request, @review_assignment]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :team_membership, label_method: proc { |team_membership| member_name(team_membership) } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/review_assignments/edit.html.erb
<% content_for(:title) do %>
  Editing Review Assignement
<% end %>

<%= render 'form' %>

<%= link_to 'Show', [@pull_request, @review_assignment] %> |
<%= link_to 'Back', pull_request_review_assignments_path(@pull_request) %>

app/views/review_assignments/index.html.erb
<% content_for(:title) do %>
  Listing Review Assignments
<% end %>

<table>
  <thead>
    <tr>
      <th>Assignee</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @review_assignments.each do |review_assignment| %>
      <tr>
        <td><%= member_name(review_assignment.team_membership) %></td>
        <td><%= link_to 'Show', pull_request_review_assignment_path(@pull_request, review_assignment) %></td>
        <td><%= link_to 'Edit', edit_pull_request_review_assignment_path(@pull_request, review_assignment) %></td>
        <td><%= link_to 'Destroy', pull_request_review_assignment_path(@pull_request, review_assignment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review Assignment', new_pull_request_review_assignment_path(@pull_request) %> |
<%= link_to 'Back', repo_pull_request_path(@pull_request.repo, @pull_request) %>

app/views/review_assignments/new.html.erb
<% content_for(:title) do %>
  New Review Assignment
<% end %>

<%= render 'form' %>

<%= link_to 'Back', pull_request_review_assignments_path(@pull_request) %>

app/views/review_assignments/show.html.erb
<% content_for(:title) do %>
  Review Assignment
<% end %>
<p>
  <strong>Pull request:</strong>
  <%= @pull_request.title %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= member_name(@review_assignment.team_membership) %>
</p>

<%= link_to 'Edit', edit_pull_request_review_assignment_path(@pull_request, @review_assignment) %> |
<%= link_to 'Back', pull_request_review_assignments_path(@pull_request) %>