config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :teams do
    resources :team_memberships
  end

  resources :repos do
    resources :pull_requests, controller: :repo_pull_requests
  end

  resources :pull_requests, only: [:new, :create] do
    resources :review_assignments
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :pull_requests, only: :create
    end
  end

  root 'welcome#index'
end

app/controllers/repo_pull_requests_controller.rb
# Controller for pull requests in a repo
class RepoPullRequestsController < ApplicationController
  respond_to :html

  load_and_authorize_resource :repo, through: :current_company

  before_action :set_pull_request,  except: :index
  before_action :set_pull_requests, only: :index

  def create
    @pull_request.save
    respond_with @repo, @pull_request
  end

  def update
    @pull_request.update(pull_request_params)
    respond_with @repo, @pull_request
  end

  def destroy
    @pull_request.destroy
    respond_with @repo, @pull_request
  end

  private

  def set_pull_request
    @pull_request =
      if params[:id]
        @repo.pull_requests.find(params[:id])
      elsif params.key?(:pull_request)
        @repo.pull_requests.build(pull_request_params)
      else
        @repo.pull_requests.build
      end
  end

  def set_pull_requests
    @pull_requests = @repo.pull_requests
  end

  def pull_request_params
    params
      .require(:pull_request)
      .permit(:repo_id, :title, :number).tap do |params|
        params[:author] = current_user
      end
  end
end

app/views/repo_pull_requests/_form.html.erb
<%= simple_form_for([@repo, @pull_request]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :repo %>
    <%= f.input :title %>
    <%= f.input :number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/repo_pull_requests/edit.html.erb
<% content_for(:title) do %>
  Editing Pull Request
<% end %>

<%= render 'form' %>

<%= link_to 'Show', repo_pull_request_path(@repo, @pull_request) %> |
<%= link_to 'Back', repo_pull_requests_path(@repo) %>

app/views/repo_pull_requests/index.html.erb
<% content_for(:title) do %>
  Listing Pull Requests
<% end %>

<table>
  <thead>
    <tr>
      <th>Repo</th>
      <th>Title</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pull_requests.each do |pull_request| %>
      <tr>
        <td><%= pull_request.repo.name %></td>
        <td><%= pull_request.title %></td>
        <td>#<%= pull_request.number %></td>
        <td><%= link_to 'Show', repo_pull_request_path(@repo, pull_request)%></td>
        <td><%= link_to 'Edit', edit_repo_pull_request_path(@repo, pull_request) %></td>
        <td><%= link_to 'Destroy', repo_pull_request_path(@repo, pull_request), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pull Request', new_repo_pull_request_path(@repo) %> |
<%= link_to 'Back', repo_path(@repo) %>

app/views/repo_pull_requests/new.html.erb
<% content_for(:title) do %>
  New Pull Request
<% end %>

<%= render 'form' %>

<%= link_to 'Back', repo_pull_requests_path(@repo) %>

app/views/repo_pull_requests/show.html.erb
<% content_for(:title) do %>
  Pull Request #<%= @pull_request.number %>
<% end %>

<p>
  <strong>Repo:</strong>
  <%= @pull_request.repo.name %>
</p>

<p>
  <strong>Author:</strong>
  <%= author_name(@pull_request.author) %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pull_request.title %>
</p>

<p>
  <strong>Number:</strong>
  #<%= @pull_request.number %>
</p>

<p>
  <strong>Review Assignments:</strong>
  <ul>
    <% @pull_request.review_assignments.each do |review_assignment| %>
      <li>
        <%= member_name(review_assignment.team_membership) %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'Manage Review Assignments', pull_request_review_assignments_path(@pull_request) %> |
<%= link_to 'Edit', edit_repo_pull_request_path(@repo, @pull_request) %> |
<%= link_to 'Back', repo_pull_requests_path(@repo) %>