config/routes.rb
Rails.application.routes.draw do
  resources :companies

  resources :teams do
    resources :team_memberships
  end

  resources :repos do
    resources :pull_requests, controller: :repo_pull_requests
  end

  resources :pull_requests, only: [:new, :create] do
    resources :review_assignments
  end

  devise_for :users

  namespace :api do
    namespace :v1 do
      resources :pull_requests, only: :create
    end
  end

  root 'welcome#index'
end

app/models/team_membership.rb
# Models memberships for teams
class TeamMembership < ActiveRecord::Base
  belongs_to :user
  belongs_to :team

  has_many :review_assignments

  validates(
    :handle,
    presence: true,
    if: proc { |membership| membership.user_id.nil? }
  )
  validates(
    :user,
    presence: true,
    if: proc { |membership| membership.handle.nil? }
  )
end

app/controllers/team_memberships_controller.rb
# Controller for managing team memberships
class TeamMembershipsController < ApplicationController
  respond_to :html

  load_and_authorize_resource :team,            through: :current_company
  load_and_authorize_resource :team_membership, through: :team

  def create
    @team_membership.save
    respond_with @team, @team_membership
  end

  def update
    @team_membership.update(team_membership_params)
    respond_with @team, @team_membership
  end

  def destroy
    @team_membership.destroy
    respond_with @team, @team_membership
  end

  private

  def team_membership_params
    params.require(:team_membership).permit(:handle, :user_id)
  end
end

app/helpers/team_memberships_helper.rb
# View helper methods for team memberships
module TeamMembershipsHelper
  def member_name(membership)
    membership.user.try(:name) || "@#{membership.handle}"
  end
end

app/views/team_memberships/_form.html.erb
<%= simple_form_for([@team, @team_membership]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :handle, autofocus: true %>
    <%= f.association :user %>
  </div>

  <div>
    <%= f.button :submit %>
  </div>
<% end %>

app/views/team_memberships/edit.html.erb
<% content_for(:title) do %>
  Editing Team Membership
<% end %>


<%= render 'form' %>

<%= link_to 'Show', [@team, @team_membership] %> |
<%= link_to 'Back', team_team_memberships_path(@team) %>

app/views/team_memberships/index.html.erb
<% content_for(:title) do %>
  Listing Team Memberships
<% end %>

<table>
  <thead>
    <tr>
      <th>Member Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_memberships.each do |team_membership| %>
      <tr>
        <td><%= member_name(team_membership) %></td>
        <td><%= link_to 'Show', team_team_membership_path(@team, team_membership) %></td>
        <td><%= link_to 'Edit', edit_team_team_membership_path(@team, team_membership) %></td>
        <td><%= link_to 'Destroy', team_team_membership_path(@team, team_membership), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Membership', new_team_team_membership_path(@team) %> |
<%= link_to 'Back', team_path(@team) %>

app/views/team_memberships/new.html.erb
<% content_for(:title) do %>
  New Team Membership
<% end %>

<%= render 'form' %>

<%= link_to 'Back', team_team_memberships_path(@team) %>

app/views/team_memberships/show.html.erb
<% content_for(:title) do %>
  <%= member_name(@team_membership) %>'s Team Membership
<% end %>

<p>
  <strong>Team:</strong>
  <%= @team.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= member_name(@team_membership) %>
</p>

<%= link_to 'Edit', edit_team_team_membership_path(@team, @team_membership) %> |
<%= link_to 'Back', team_team_memberships_path(@team) %>